/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import analises.AnaliseSintatica;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author valter
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private String arqCodigo;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setSize(540, 480);
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        int larguraDaTela = tela.width;
        int alturaDaTela = tela.height;
        this.setLocation((larguraDaTela - 540) / 2, (alturaDaTela - 480) / 2);
        this.arqCodigo = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcAbrir = new javax.swing.JFileChooser();
        jfcSalvar = new javax.swing.JFileChooser();
        jpCodigo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCodigo = new javax.swing.JTextArea();
        jbCompilar = new javax.swing.JButton();
        jmbCompilador = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiAbrir = new javax.swing.JMenuItem();
        jmiNovoArquivo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        JmiSalvar = new javax.swing.JMenuItem();
        jmiSalvarComo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();

        jfcAbrir.setDialogTitle("Abrir...");
        jfcAbrir.setFileFilter(new MyCustomFilter());

        jfcSalvar.setDialogTitle("Salvar...");
        jfcSalvar.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 800));

        jpCodigo.setLayout(new java.awt.BorderLayout());

        jtaCodigo.setColumns(20);
        jtaCodigo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jtaCodigo.setRows(5);
        jtaCodigo.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(jtaCodigo);

        jpCodigo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpCodigo, java.awt.BorderLayout.CENTER);

        jbCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compilar.png"))); // NOI18N
        jbCompilar.setText("Compilar");
        jbCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCompilarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCompilar, java.awt.BorderLayout.SOUTH);

        jmArquivo.setText("Arquivo");

        jmiAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abrir.png"))); // NOI18N
        jmiAbrir.setText("Abrir Arquivo...");
        jmiAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrirActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiAbrir);

        jmiNovoArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        jmiNovoArquivo.setText("Novo Arquivo Fonte...");
        jmiNovoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovoArquivoActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiNovoArquivo);
        jmArquivo.add(jSeparator2);

        JmiSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        JmiSalvar.setText("Salvar");
        JmiSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiSalvarActionPerformed(evt);
            }
        });
        jmArquivo.add(JmiSalvar);

        jmiSalvarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar como.png"))); // NOI18N
        jmiSalvarComo.setText("Salvar como...");
        jmiSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalvarComoActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSalvarComo);
        jmArquivo.add(jSeparator1);

        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSair);

        jmbCompilador.add(jmArquivo);

        setJMenuBar(jmbCompilador);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCompilarActionPerformed
        AnaliseSintatica as = new AnaliseSintatica(jtaCodigo.getText());
    }//GEN-LAST:event_jbCompilarActionPerformed

    private void jmiAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrirActionPerformed
        int returnVal = jfcAbrir.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfcAbrir.getSelectedFile();
            arqCodigo = file.getAbsolutePath();
            try {
              // What to do with the file, e.g. display it in a TextArea
              jtaCodigo.read(new FileReader(arqCodigo), null);
            } catch (IOException ex) {
              System.out.println("Ocorreu um problema acessando o arquivo" + file.getAbsolutePath());
            }
        } else {
            System.out.println("Acesso ao arquivo cancelada pelo usuário.");
        }
    }//GEN-LAST:event_jmiAbrirActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiNovoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovoArquivoActionPerformed
        jtaCodigo.setText("");
        this.arqCodigo = "";
    }//GEN-LAST:event_jmiNovoArquivoActionPerformed

    private void JmiSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiSalvarActionPerformed
        if (arqCodigo.equals(""))
            salvarArquivoComo();
        else salvarArquivo();
    }//GEN-LAST:event_JmiSalvarActionPerformed

    private void jmiSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalvarComoActionPerformed
        salvarArquivoComo();
    }//GEN-LAST:event_jmiSalvarComoActionPerformed

    private void salvarArquivo() {
        try {
            File arquivo = new File(arqCodigo);
            PrintWriter pw = new PrintWriter(arquivo);
            pw.write(jtaCodigo.getText());
            pw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void salvarArquivoComo() {
        jfcSalvar.setDialogTitle("Salvar Arquivo");
        jfcSalvar.setCurrentDirectory(new File("."));
        int select = jfcSalvar.showSaveDialog(null);
        
        if (select == JFileChooser.APPROVE_OPTION) {
            try {
                File arquivo = jfcSalvar.getSelectedFile();
                PrintWriter pw = new PrintWriter(arquivo);
                pw.write(jtaCodigo.getText());
                pw.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmiSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton jbCompilar;
    private javax.swing.JFileChooser jfcAbrir;
    private javax.swing.JFileChooser jfcSalvar;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenuBar jmbCompilador;
    private javax.swing.JMenuItem jmiAbrir;
    private javax.swing.JMenuItem jmiNovoArquivo;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSalvarComo;
    private javax.swing.JPanel jpCodigo;
    private javax.swing.JTextArea jtaCodigo;
    // End of variables declaration//GEN-END:variables
}
